### ISSUE TITLE
Could you provide dataset links in google drive or one drive?

### ISSUE THREAD

**Issue by wooseok-song** [bcmi/Rendered-Shadow-Generation-Dataset-RdSOBA#1]
Could you provide dataset links in google drive or one drive? 

I'm planning to do experiments on RdSOBA!

**Comment by taoxinhao13** [comment]
Hello, we've added the OneDrive link for a partial of our RdSOBA.

**Comment by zhangpzh** [comment]
I would like to ask the same question. It is so important that the authors could provide the GoogleDrive link. In nowadays laboratory in university or other affiliation, the information security is controlled rigorously. BaiduDisk requires us to install its own app which is not allowed to do so in the laboratory computers. Adding link to GoogleDrive will undoubtedly increase your work's impact.

**Comment by zhangpzh** [comment]
> Hello, we've added the OneDrive link for a partial of our RdSOBA.

Hi, may I know where you put this link ? I didn't see anyone in the README.md main page.

**Comment by taoxinhao13** [comment]
We have updated the link to the full version of the RdSOBA dataset a few days ago. However, due to the large size of the dataset, the OneDrive link is still being prepared. We expect to release it within the next couple of days.

**Comment by zhangpzh** [comment]
> We have updated the link to the full version of the RdSOBA dataset a few days ago. However, due to the large size of the dataset, the OneDrive link is still being prepared. We expect to release it within the next couple of days.
Ok, thanks for the in-time reply.

**Comment by zhangpzh** [comment]
> We have updated the link to the full version of the RdSOBA dataset a few days ago. However, due to the large size of the dataset, the OneDrive link is still being prepared. We expect to release it within the next couple of days.

Ok, thanks for the in-time reply.

**Comment by taoxinhao13** [comment]
We have updated the OneDrive link. Have fun. :)
