### ISSUE TITLE
Algorithm not found in libcom

### ISSUE THREAD

**Issue by zhangpzh** [bcmi/Rendered-Shadow-Generation-Dataset-RdSOBA#2]
I admire your libcom tools which are with elaborated documentation. I see the ambition of your laboratory that want to create a standard for harmonization, shadow generation and even inpainting field, just like cv2 in computer vision community. But it seems the source codes are not provided that means us community researchers / engineers is hard to fine-tune your proposed model on our dataset ?
And your proposed DMASNet is not relevant to the shadow_generation_api in the libcom ?  I found that for this api, there is no input requirement for background object shadow (will attend the shadow filling and mean transfer as mentioned in this paper).

**Comment by ustcnewly** [comment]
In the "method summary" in https://libcom.readthedocs.io/en/latest/harmony_score.html, you can find the link to source code for each method. You can finetune on your own data.
For shadow generation https://libcom.readthedocs.io/en/latest/shadow_generation.html, we train ControlNet using our DESOBAv2 dataset https://github.com/bcmi/Object-Shadow-Generation-Dataset-DESOBAv2. The full dataset will be released soon. It is not related to DMASNet.

**Comment by zhangpzh** [comment]
Thank your for your reply. Since I read ControlCom and DMASNet paper recently and I found their source codes were not released. Simultaneously, I happen to see the libcom tool. These make me subconciously think the previously mentioned methods are not open-sourced anymore, only encapsulated binaries api are provided.  Now I see. I think I gotta wait for the open-sourcing. By the way, it seems the ControlNet-based shadow inpainting scheme is neater than that in DMASNet. Have your ever compare the shadow generation quality between both methods. Thank you for the response, again.

**Comment by ustcnewly** [comment]
ControlNet-based method achieves much better results, due to the training set and foundation model.
